# Use the Node.js image as base
FROM node:20

# Create a working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port your application will listen on
EXPOSE 4001

# Command to start the application
CMD ["npm", "start"]