version: '3.8'

services:
  app:
    build: .
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/postgres
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx sequelize-cli db:migrate && npm start"  # Cambiar aquí

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
